import React, { useState } from 'react';
import { FullRepoData } from '../types';
import { Download, FileText, Code, Check, X, Printer } from 'lucide-react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  repoData: FullRepoData | null;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, repoData }) => {
  const [downloadedFormat, setDownloadedFormat] = useState<string | null>(null);

  if (!isOpen || !repoData) return null;

  const handleDownloadMarkdown = () => {
    const md = `# Architectural Review Report: ${repoData.info.fullName}
Generated by GitHub Analyzer SaaS Studio on ${new Date().toLocaleDateString()}

## 1. Overview
- **Repository:** ${repoData.info.fullName}
- **Description:** ${repoData.info.description || 'N/A'}
- **Stars:** ${repoData.info.stats.stars.toLocaleString()} | **Forks:** ${repoData.info.stats.forks.toLocaleString()} | **Open Issues:** ${repoData.info.stats.openIssues.toLocaleString()}
- **Primary Language:** ${repoData.info.language || 'Multi-language'}
- **License:** ${repoData.info.license || 'N/A'}
- **GitHub URL:** ${repoData.info.htmlUrl}

## 2. AI Architectural Review
- **Health Score:** ${repoData.aiReview.healthScore}/100 (${repoData.aiReview.statusLabel})
- **Executive Summary:** ${repoData.aiReview.executiveSummary}

### Key Strengths
${repoData.aiReview.strengths.map((s) => `- **${s.title}:** ${s.description}`).join('\n')}

### Maintenance Risks
${repoData.aiReview.risks.map((r) => `- **${r.title}:** ${r.description}`).join('\n')}

### Actionable Recommendations
${repoData.aiReview.recommendations.map((rec) => `- **${rec.title}:** ${rec.description}`).join('\n')}

## 3. Metrics Signal Breakdown
- **Documentation Quality:** ${repoData.aiReview.metrics.documentationQuality}%
- **Test Coverage Signal:** ${repoData.aiReview.metrics.testCoverageSignal}%
- **Maintenance Liveliness:** ${repoData.aiReview.metrics.maintenanceLiveliness}%
- **Community Engagement:** ${repoData.aiReview.metrics.communityEngagement}%
`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${repoData.info.name}-architectural-report.md`;
    a.click();
    URL.revokeObjectURL(url);

    setDownloadedFormat('Markdown');
    setTimeout(() => setDownloadedFormat(null), 2000);
  };

  const handleDownloadJson = () => {
    const jsonStr = JSON.stringify(repoData, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${repoData.info.name}-analysis-data.json`;
    a.click();
    URL.revokeObjectURL(url);

    setDownloadedFormat('JSON');
    setTimeout(() => setDownloadedFormat(null), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-fadeIn">
      <div className="relative w-full max-w-md p-6 rounded-2xl bg-slate-900 border border-slate-800 shadow-2xl">
        
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center gap-3 mb-5">
          <div className="p-2.5 rounded-xl bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
            <Download className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-white">Export Analysis Report</h3>
            <p className="text-xs text-slate-400">Choose your preferred export format for {repoData.info.name}</p>
          </div>
        </div>

        <div className="space-y-3 mb-6">
          <button
            onClick={handleDownloadMarkdown}
            className="w-full p-4 rounded-xl bg-slate-950 border border-slate-800 hover:border-indigo-500/50 flex items-center justify-between text-left transition-all group"
          >
            <div className="flex items-center gap-3">
              <FileText className="w-5 h-5 text-indigo-400" />
              <div>
                <div className="text-sm font-bold text-white group-hover:text-indigo-300">Markdown Architectural Report (.md)</div>
                <div className="text-xs text-slate-400">Formatted summary with strengths, risks & recommendations</div>
              </div>
            </div>
            {downloadedFormat === 'Markdown' ? <Check className="w-5 h-5 text-emerald-400" /> : <Download className="w-4 h-4 text-slate-500 group-hover:text-white" />}
          </button>

          <button
            onClick={handleDownloadJson}
            className="w-full p-4 rounded-xl bg-slate-950 border border-slate-800 hover:border-indigo-500/50 flex items-center justify-between text-left transition-all group"
          >
            <div className="flex items-center gap-3">
              <Code className="w-5 h-5 text-purple-400" />
              <div>
                <div className="text-sm font-bold text-white group-hover:text-purple-300">Raw Analysis Data (.json)</div>
                <div className="text-xs text-slate-400">Full JSON payload including stats, commits, and AI review</div>
              </div>
            </div>
            {downloadedFormat === 'JSON' ? <Check className="w-5 h-5 text-emerald-400" /> : <Download className="w-4 h-4 text-slate-500 group-hover:text-white" />}
          </button>

          <button
            onClick={handlePrint}
            className="w-full p-4 rounded-xl bg-slate-950 border border-slate-800 hover:border-indigo-500/50 flex items-center justify-between text-left transition-all group"
          >
            <div className="flex items-center gap-3">
              <Printer className="w-5 h-5 text-emerald-400" />
              <div>
                <div className="text-sm font-bold text-white group-hover:text-emerald-300">Print or Save as PDF</div>
                <div className="text-xs text-slate-400">Open system print dialog for PDF generation</div>
              </div>
            </div>
            <Printer className="w-4 h-4 text-slate-500 group-hover:text-white" />
          </button>
        </div>

        <div className="flex justify-end pt-2">
          <button
            onClick={onClose}
            className="px-4 py-2 text-xs font-semibold text-slate-400 hover:text-white"
          >
            Close
          </button>
        </div>

      </div>
    </div>
  );
};
